import Available from '@/components/UI/Available';
import Beta from '@/components/UI/Beta';
import Enhanced from '@/components/UI/Enhanced';
import FAQ from '@/components/UI/FAQ';
import Hero from '@/components/UI/Hero';
import Navbar from '@/components/UI/Navbar';
import ProductDisp from '@/components/UI/ProductDisp';
import Testimonials from '@/components/UI/Testimonials';
import Works from '@/components/UI/Works';
import Head from 'next/head';
import styled from 'styled-components';

export default function Home() {
  return (
    <>
      <Head>
        <title>PocketPal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://api.fontshare.com/v2/css?f[]=clash-display@200,400,700,500,600,300&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main>
        <Section>
          <Navbar />
          <Hero />
        </Section>
        <ProductDisp />
        <Works />
        <Enhanced />
        <Beta />
        <Testimonials />
        <FAQ />
        <Available />
      </main>
    </>
  );
}

const Section = styled.section`
  background: #87ceeb;
`;
