import Hero from '@/components/UI/Hero';
import Navbar from '@/components/UI/Navbar';
import Head from 'next/head';
import styled from 'styled-components';

export default function Home() {
  return (
    <>
      <Head>
        <title>PocketPal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://api.fontshare.com/v2/css?f[]=clash-display@200,400,700,500,600,300&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main>
        <Section>
          <Navbar />
          <Hero />
        </Section>
      </main>
    </>
  );
}

const Section = styled.section`
  background: #87ceeb;
  min-height: 100vh;
`;
